version: "3"
services:
  db:
    image: postgres:15.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
