server:
  port: 9090

secret: =======================Spring===========================
expiration: 86400000

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/test?currentSchema=social_media}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging.level:
  org.springframework.security: DEBUG